// Phase 3: Fast Broadcast.
//
// POST /api/broadcast — send one content / remote URL / playlist to a selection
// of displays in ~2 taps, reusing the existing device-content-push path
// (services/scene-engine.pushSourceToDevice -> commandQueue device:playlist-update).
//
// Confirmation gate: if the target set equals ALL devices in the caller's
// workspace AND confirm_all !== true, respond 409 { code:'CONFIRM_ALL_REQUIRED',
// count } so the UI can show a "you're about to take over every display"
// confirmation before re-submitting with confirm_all:true.
//
// Mounted with requireAuth + resolveTenancy (server.js). Writes deny
// workspace_viewer (mirrors playlists.js / scenes.js).

const express = require('express');
const router = express.Router();
const { db } = require('../db/database');
const sceneEngine = require('../services/scene-engine');
const { logActivity, getClientIp } = require('../services/activity');
const { deckPlayerUrl } = require('../lib/deck-player-url');
const { assertRemoteUrlSafe } = require('../lib/ssrf-policy');
const { audit } = require('../lib/audit');
const { ensureLiveStreamDisplay, liveStreamProgramState, markLiveContentChanged } = require('../lib/live-stream-display');
const {
  LIVE_STREAM_DEVICE_PREFIX,
  isManagedLiveStreamTarget,
  resolveBroadcastTargets,
  resolveTypedBroadcastTargets,
} = require('../lib/broadcast-targets');
const nodeRegistry = require('../lib/node-registry');
const { contentUseDecision, contextFromRequest } = require('../lib/content-visibility');

async function callDirector(path, body) {
  const base = String(process.env.AI_DIRECTOR_URL || 'http://host.docker.internal:8766').replace(/\/+$/, '');
  if (!base) return { ok: false, message: 'AI Director URL not configured' };
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), Number(process.env.AI_DIRECTOR_TIMEOUT_MS) || 8000);
  try {
    const response = await fetch(`${base}${path}`, {
      method: 'POST',
      headers: body ? { 'Content-Type': 'application/json' } : undefined,
      body: body ? JSON.stringify(body) : undefined,
      signal: controller.signal,
    });
    const text = await response.text();
    let data = null;
    try { data = text ? JSON.parse(text) : null; } catch { data = text; }
    return { ok: response.ok, status: response.status, data };
  } catch (e) {
    return { ok: false, message: e && e.message || 'AI Director request failed' };
  } finally {
    clearTimeout(timeout);
  }
}

router.post('/', async (req, res) => {
  if (!req.workspaceId) return res.status(400).json({ error: 'No active workspace' });
  if (!req.actingAs && req.workspaceRole === 'workspace_viewer') {
    return res.status(403).json({ error: 'Read-only access' });
  }

  const {
    device_ids, targets: target_refs, content_id, remote_url, playlist_id, presentation_id, fit_mode, confirm_all, include_live_stream,
  } = req.body || {};

  // Validate the target selection.
  if (device_ids !== undefined && !Array.isArray(device_ids)) {
    return res.status(400).json({ error: 'device_ids must be an array' });
  }
  if (target_refs !== undefined && !Array.isArray(target_refs)) {
    return res.status(400).json({ error: 'targets must be an array' });
  }
  const legacyIds = Array.isArray(device_ids) ? device_ids : [];
  const typedRefs = Array.isArray(target_refs) ? target_refs : [];
  if (legacyIds.length === 0 && typedRefs.length === 0 && include_live_stream !== true) {
    return res.status(400).json({ error: 'device_ids or targets must select at least one display unless Live Program is explicitly selected' });
  }

  // Validate at least one source (presentation_id counts as a valid source).
  if (!content_id && !remote_url && !playlist_id && !presentation_id) {
    return res.status(400).json({ error: 'one of content_id, remote_url, playlist_id, or presentation_id is required' });
  }
  if (content_id) {
    const decision = contentUseDecision(db, String(content_id), req.workspaceId, contextFromRequest(req));
    if (!decision.content) return res.status(404).json({ error: 'Content not found' });
    if (!decision.allowed) return res.status(403).json({ error: decision.reason });
  }

  // SSRF gate: a hand-typed remote_url is broadcast straight to displays. Run
  // the centralized policy (shape + DNS resolution) so it can't point a display
  // at internal infra / metadata. A presentation_id-derived URL is generated by
  // us (our own public host) below and isn't user-controlled, so it's exempt.
  if (remote_url) {
    const safe = await assertRemoteUrlSafe(remote_url);
    if (!safe.ok) return res.status(400).json({ error: safe.error });
  }

  // Resolve a presentation_id to its public deck-player remote_url, so a deck
  // flows through the SAME source/push path as a hand-typed remote_url (exactly
  // what the "Present this deck" buttons already broadcast). The presentation
  // must exist and live in the caller's workspace.
  let effectiveRemoteUrl = remote_url;
  if (presentation_id) {
    const pres = db.prepare('SELECT id, workspace_id FROM presentations WHERE id = ?').get(String(presentation_id));
    if (!pres) return res.status(404).json({ error: `Presentation ${presentation_id} not found` });
    if (pres.workspace_id !== req.workspaceId) {
      return res.status(403).json({ error: `Presentation ${presentation_id} is not in this workspace` });
    }
    const publicBase = process.env.APP_URL || `${req.protocol}://${req.get('host')}`;
    effectiveRemoteUrl = deckPlayerUrl(publicBase, pres.id);
  }

  // Resolve logical targets from authoritative, current topology before any
  // display mutation. Wall targets carry an optimistic layout revision: stale
  // popup/card selections fail atomically instead of broadcasting to an old
  // physical membership list supplied by the browser.
  const typedResolution = resolveTypedBroadcastTargets({
    db,
    refs: typedRefs,
    workspaceId: req.workspaceId,
  });
  if (!typedResolution.ok) return res.status(typedResolution.status).json(typedResolution.body);

  // Merge the revision-safe logical selection with legacy physical ids. The
  // legacy contract remains compatible while new clients can use typed refs.
  const requested = [...new Set(
    typedRefs.length > 0 ? typedResolution.targets : legacyIds.map(String)
  )];
  // Live Program is represented only by its explicit boolean gate. Ignore any
  // legacy managed id here and recreate/append the workspace's canonical live
  // target only after validation and confirm-all have completed.
  const requestedPhysical = requested.filter((id) => !isManagedLiveStreamTarget(id));
  let resolvedTargets = resolveBroadcastTargets({
    db,
    requestedIds: requestedPhysical,
    workspaceId: req.workspaceId,
    allowLiveStream: false,
  });
  if (!resolvedTargets.ok) {
    if (include_live_stream === true && resolvedTargets.status === 404) {
      resolvedTargets = {
        ok: true,
        requested: requestedPhysical,
        targets: [],
        missing: resolvedTargets.body?.missing || requestedPhysical,
      };
    } else {
      return res.status(resolvedTargets.status).json(resolvedTargets.body);
    }
  }
  const physicalTargets = resolvedTargets.targets;

  // Confirmation gate when targeting ALL displays in the workspace.
  const totalInWorkspace = db.prepare(
    `SELECT COUNT(*) AS c FROM devices
     WHERE workspace_id = ?
       AND id NOT LIKE ?`
  ).get(req.workspaceId, `${LIVE_STREAM_DEVICE_PREFIX}%`).c;
  const targetingAll = totalInWorkspace > 0 && physicalTargets.length === totalInWorkspace;
  if (targetingAll && confirm_all !== true) {
    return res.status(409).json({ code: 'CONFIRM_ALL_REQUIRED', count: totalInWorkspace });
  }

  // All read-only validation and the operator confirmation gate have passed.
  // Only now may the request create/mark the managed Live Program display.
  const targets = [...physicalTargets];
  if (include_live_stream === true) {
    const liveStreamDisplay = ensureLiveStreamDisplay({ workspaceId: req.workspaceId, userId: req.user.id });
    if (liveStreamDisplay && !targets.includes(liveStreamDisplay.id)) targets.push(liveStreamDisplay.id);
    if (liveStreamDisplay) markLiveContentChanged(liveStreamDisplay.id);
  }

  const source = { content_id, remote_url: effectiveRemoteUrl, playlist_id, fit_mode };
  const io = req.app.get('io');
  const totalRequested = targets.length + resolvedTargets.missing.length;
  let sent = 0;
  const failed = resolvedTargets.missing.slice();
  for (const deviceId of targets) {
    const ok = sceneEngine.pushSourceToDevice(io, deviceId, source, {
      workspaceId: req.workspaceId,
      userId: req.user.id,
      contentContext: contextFromRequest(req),
      targetDeviceIds: targets,
    });
    if (ok) sent++; else failed.push(deviceId);
  }
  // The device playlist assignment above is the authorization event that makes
  // the asset eligible for the room node. Prewarm only after that transaction;
  // upload-time library scans must never expose unassigned private content.
  const cachePrewarm = content_id
    ? nodeRegistry.requestContentPrewarm(io, db, { deviceIds: targets, contentId: content_id })
    : { requested: false, reason: 'not_local_content' };

  // Log the broadcast (activityLogger middleware only captures a single
  // device_id; broadcasts touch many, so log an explicit summary here).
  try {
    const sourceLabel = presentation_id ? `presentation:${presentation_id}`
      : playlist_id ? `playlist:${playlist_id}`
      : content_id ? `content:${content_id}`
      : `url:${effectiveRemoteUrl}`;
    logActivity(
      req.user.id,
      'POST /api/broadcast',
      `broadcast ${sourceLabel} to ${sent}/${totalRequested} display(s)${targetingAll ? ' (ALL)' : ''}`,
      null,
      getClientIp(req),
      req.workspaceId
    );
  } catch (e) { /* logging best-effort */ }

  // Security audit trail (redacted; never stores token-bearing query strings).
  audit({
    actorType: 'user',
    actorId: req.user.id,
    action: 'display.broadcast',
    targetType: 'workspace',
    targetId: req.workspaceId,
    workspaceId: req.workspaceId,
    sourceIp: getClientIp(req),
    details: {
      source: presentation_id ? 'presentation' : playlist_id ? 'playlist' : content_id ? 'content' : 'remote_url',
      content_id: content_id || null,
      playlist_id: playlist_id || null,
      presentation_id: presentation_id || null,
      remote_url: effectiveRemoteUrl || null,
      device_ids: targets,
      target_count: totalRequested,
      missing_device_count: resolvedTargets.missing.length,
      sent,
      targeting_all: targetingAll,
      cache_prewarm_requested: cachePrewarm.requested === true,
    },
  });

  let liveProgram = null;
  if (include_live_stream === true) {
    liveProgram = liveStreamProgramState(req.workspaceId);
    liveProgram.program_refresh = await callDirector('/media-control/refresh');
  }
  res.json({ success: true, sent, failed, total: totalRequested, cache_prewarm: cachePrewarm, live_stream: liveProgram });
});

module.exports = router;
