// Phase 3: Fast Broadcast.
//
// POST /api/broadcast — send one content / remote URL / playlist to a selection
// of displays in ~2 taps, reusing the existing device-content-push path
// (services/scene-engine.pushSourceToDevice -> commandQueue device:playlist-update).
//
// Confirmation gate: if the target set equals ALL devices in the caller's
// workspace AND confirm_all !== true, respond 409 { code:'CONFIRM_ALL_REQUIRED',
// count } so the UI can show a "you're about to take over every display"
// confirmation before re-submitting with confirm_all:true.
//
// Mounted with requireAuth + resolveTenancy (server.js). Writes deny
// workspace_viewer (mirrors playlists.js / scenes.js).

const express = require('express');
const router = express.Router();
const { db } = require('../db/database');
const sceneEngine = require('../services/scene-engine');
const { logActivity, getClientIp } = require('../services/activity');
const { deckPlayerUrl } = require('../lib/deck-player-url');
const { assertRemoteUrlSafe } = require('../lib/ssrf-policy');
const { audit } = require('../lib/audit');
const { ensureLiveStreamDisplay, liveStreamProgramState, markLiveContentChanged } = require('../lib/live-stream-display');

async function notifyLiveProgramUrl(req, url) {
  const base = String(process.env.AI_DIRECTOR_URL || 'http://host.docker.internal:8766').replace(/\/+$/, '');
  if (!url || !base) return { ok: false, message: 'missing url or AI Director URL' };
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), Number(process.env.AI_DIRECTOR_TIMEOUT_MS) || 8000);
  try {
    const response = await fetch(`${base}/media-control/program-url`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url }),
      signal: controller.signal,
    });
    const text = await response.text();
    let data = null;
    try { data = text ? JSON.parse(text) : null; } catch { data = text; }
    return { ok: response.ok, status: response.status, data };
  } catch (e) {
    return { ok: false, message: e && e.message || 'AI Director update failed' };
  } finally {
    clearTimeout(timeout);
  }
}

router.post('/', async (req, res) => {
  if (!req.workspaceId) return res.status(400).json({ error: 'No active workspace' });
  if (!req.actingAs && req.workspaceRole === 'workspace_viewer') {
    return res.status(403).json({ error: 'Read-only access' });
  }

  const {
    device_ids, content_id, remote_url, playlist_id, presentation_id, fit_mode, confirm_all, include_live_stream,
  } = req.body || {};

  // Validate the target selection.
  if (!Array.isArray(device_ids) || device_ids.length === 0) {
    return res.status(400).json({ error: 'device_ids must be a non-empty array' });
  }

  // Validate at least one source (presentation_id counts as a valid source).
  if (!content_id && !remote_url && !playlist_id && !presentation_id) {
    return res.status(400).json({ error: 'one of content_id, remote_url, playlist_id, or presentation_id is required' });
  }

  // SSRF gate: a hand-typed remote_url is broadcast straight to displays. Run
  // the centralized policy (shape + DNS resolution) so it can't point a display
  // at internal infra / metadata. A presentation_id-derived URL is generated by
  // us (our own public host) below and isn't user-controlled, so it's exempt.
  if (remote_url) {
    const safe = await assertRemoteUrlSafe(remote_url);
    if (!safe.ok) return res.status(400).json({ error: safe.error });
  }

  // Resolve a presentation_id to its public deck-player remote_url, so a deck
  // flows through the SAME source/push path as a hand-typed remote_url (exactly
  // what the "Present this deck" buttons already broadcast). The presentation
  // must exist and live in the caller's workspace.
  let effectiveRemoteUrl = remote_url;
  if (presentation_id) {
    const pres = db.prepare('SELECT id, workspace_id FROM presentations WHERE id = ?').get(String(presentation_id));
    if (!pres) return res.status(404).json({ error: `Presentation ${presentation_id} not found` });
    if (pres.workspace_id !== req.workspaceId) {
      return res.status(403).json({ error: `Presentation ${presentation_id} is not in this workspace` });
    }
    const publicBase = process.env.APP_URL || `${req.protocol}://${req.get('host')}`;
    effectiveRemoteUrl = deckPlayerUrl(publicBase, pres.id);
  }

  // De-dupe and confirm every target device is in this workspace.
  const requested = [...new Set(device_ids.map(String))];
  if (include_live_stream === true) {
    const liveStreamDisplay = ensureLiveStreamDisplay({ workspaceId: req.workspaceId, userId: req.user.id });
    if (liveStreamDisplay && !requested.includes(liveStreamDisplay.id)) requested.push(liveStreamDisplay.id);
    if (liveStreamDisplay) markLiveContentChanged(liveStreamDisplay.id);
  }
  const targets = [];
  for (const id of requested) {
    const device = db.prepare('SELECT id, workspace_id FROM devices WHERE id = ?').get(id);
    if (!device) return res.status(404).json({ error: `Device ${id} not found` });
    if (device.workspace_id !== req.workspaceId) {
      return res.status(403).json({ error: `Device ${id} is not in this workspace` });
    }
    targets.push(id);
  }

  // Confirmation gate when targeting ALL displays in the workspace.
  const totalInWorkspace = db.prepare(
    'SELECT COUNT(*) AS c FROM devices WHERE workspace_id = ?'
  ).get(req.workspaceId).c;
  const targetingAll = totalInWorkspace > 0 && targets.length === totalInWorkspace;
  if (targetingAll && confirm_all !== true) {
    return res.status(409).json({ code: 'CONFIRM_ALL_REQUIRED', count: totalInWorkspace });
  }

  const source = { content_id, remote_url: effectiveRemoteUrl, playlist_id, fit_mode };
  const io = req.app.get('io');

  let sent = 0;
  const failed = [];
  for (const deviceId of targets) {
    const ok = sceneEngine.pushSourceToDevice(io, deviceId, source, {
      workspaceId: req.workspaceId,
      userId: req.user.id,
    });
    if (ok) sent++; else failed.push(deviceId);
  }

  // Log the broadcast (activityLogger middleware only captures a single
  // device_id; broadcasts touch many, so log an explicit summary here).
  try {
    const sourceLabel = presentation_id ? `presentation:${presentation_id}`
      : playlist_id ? `playlist:${playlist_id}`
      : content_id ? `content:${content_id}`
      : `url:${effectiveRemoteUrl}`;
    logActivity(
      req.user.id,
      'POST /api/broadcast',
      `broadcast ${sourceLabel} to ${sent}/${targets.length} display(s)${targetingAll ? ' (ALL)' : ''}`,
      null,
      getClientIp(req),
      req.workspaceId
    );
  } catch (e) { /* logging best-effort */ }

  // Security audit trail (redacted; never stores token-bearing query strings).
  audit({
    actorType: 'user',
    actorId: req.user.id,
    action: 'display.broadcast',
    targetType: 'workspace',
    targetId: req.workspaceId,
    workspaceId: req.workspaceId,
    sourceIp: getClientIp(req),
    details: {
      source: presentation_id ? 'presentation' : playlist_id ? 'playlist' : content_id ? 'content' : 'remote_url',
      content_id: content_id || null,
      playlist_id: playlist_id || null,
      presentation_id: presentation_id || null,
      remote_url: effectiveRemoteUrl || null,
      target_count: targets.length,
      sent,
      targeting_all: targetingAll,
    },
  });

  let liveProgram = null;
  if (include_live_stream === true) {
    liveProgram = liveStreamProgramState(req.workspaceId);
    if (effectiveRemoteUrl) liveProgram.program_url_update = await notifyLiveProgramUrl(req, effectiveRemoteUrl);
  }
  res.json({ success: true, sent, failed, total: targets.length, live_stream: liveProgram });
});

module.exports = router;
