'use strict';

// Task §6 — Real-browser console acceptance (Media Control release branch).
//
// Runs in BOTH Chromium and Firefox (see playwright.browser-console.config.js)
// at the three operator viewport sizes (1366x768, 1440x900, 1920x1080) against
// the REAL server + REAL frontend (no mocks). A clean browser profile (no
// extensions) is used so extension-owned noise like installHook.js.map cannot
// be mis-counted as an application defect.
//
// Fail conditions (per task §6):
//   • Feature Policy warnings generated by application iframes
//   • Clear-Site-Data warnings during normal application loading
//   • JavaScript errors
//   • CSS parsing errors
//   • unhandled promise rejections
//   • screenshot 401 responses
//   • duplicate Socket.IO connections
//   • unintended page reloads
//   • application-owned source-map errors
// Also verifies the stable keyed render (task §4): routine state pings must not
// recreate preview iframes (window.__mcStageMetrics.iframeCreates stays ~0 after
// the initial mount while no structural change occurs).

const { test, expect } = require('@playwright/test');
const { spawn, execSync } = require('child_process');
const path = require('path');
const fs = require('fs');
const os = require('os');

const SERVER_DIR = path.resolve(__dirname, '..', '..');
const PORT = 18117; // distinct from real-app (18099) and service-worker (18116)
const BASE_URL = `http://127.0.0.1:${PORT}`;
const JWT_SECRET = 'browser-console-playwright-test-jwt-secret-hs256-min-length-ok';
const TEST_EMAIL = 'browserconsole@test.local';
const TEST_PASSWORD = 'browser-console-test-password';
const TEST_NAME = 'Console Test';

const VIEWPORTS = [
  { width: 1366, height: 768 },
  { width: 1440, height: 900 },
  { width: 1920, height: 1080 },
];

let serverProcess = null;
let tmpDir = '';
let authToken = '';
let authUser = null;
let serverLogs = [];

function killServer() {
  if (!serverProcess) return;
  const pid = serverProcess.pid;
  try {
    if (process.platform === 'win32') execSync(`taskkill /pid ${pid} /T /F`, { stdio: 'ignore' });
    else process.kill(pid, 'SIGKILL');
  } catch { /* best-effort */ }
  serverProcess = null;
}

function startServer() {
  killServer();
  if (tmpDir) { try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch {} }
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mc-browserconsole-'));
  const dbPath = path.join(tmpDir, 'test.db');
  const env = {
    ...process.env,
    PORT: String(PORT),
    DB_PATH: dbPath,
    JWT_SECRET: JWT_SECRET,
    NODE_ENV: 'development',
    DISABLE_REGISTRATION: 'false',
    SELF_HOSTED: 'true',
    ENTERPRISE_OPERATOR_UI_ENABLED: 'true',
    ENTERPRISE_OPERATOR_UI_USERS: '',
    PLAYER_DEBUG_REPORTING: 'off',
  };
  serverLogs = [];
  serverProcess = spawn(process.execPath, ['server.js'], { cwd: SERVER_DIR, env, stdio: ['pipe', 'pipe', 'pipe'] });
  serverProcess.stdout.on('data', (d) => serverLogs.push(d.toString()));
  serverProcess.stderr.on('data', (d) => serverLogs.push(`[stderr] ${d.toString()}`));
  serverProcess.on('exit', (code, signal) => serverLogs.push(`[server exited code=${code} signal=${signal}]`));
  return waitForServer();
}

async function waitForServer(timeoutMs = 45000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (serverProcess && serverProcess.exitCode !== null && serverProcess.exitCode !== undefined) {
      throw new Error(`Server exited early (code=${serverProcess.exitCode}).\nRecent logs:\n${serverLogs.slice(-50).join('')}`);
    }
    try {
      const res = await fetch(`${BASE_URL}/api/version`);
      if (res.ok) return;
    } catch {}
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`Server did not respond within ${timeoutMs}ms.\nRecent logs:\n${serverLogs.slice(-50).join('')}`);
}

async function registerTestUser() {
  const res = await fetch(`${BASE_URL}/api/auth/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: TEST_EMAIL, password: TEST_PASSWORD, name: TEST_NAME }),
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(`Registration failed (${res.status}): ${JSON.stringify(body)}`);
  }
  const body = await res.json();
  authToken = body.token;
  authUser = body.user;
  return body;
}

// Console collector tuned to the task §6 failure classes. Feature Policy
// warnings appear as console "warning"/"error" messages containing the
// canonical substrings; Clear-Site-Data appears as a warning; CSS parse errors
// carry "Could not parse CSS"; source-map 404s carry ".map".
function attachConsoleCollectors(page) {
  const collected = {
    featurePolicy: [],
    clearSiteData: [],
    jsErrors: [],
    cssErrors: [],
    rejections: [],
    screenshot401: [],
    sourceMapErrors: [],
    otherConsoleErrors: [],
    socketConnectCount: 0,
    reloadCount: 0,
  };
  page.on('console', (msg) => {
    const text = msg.text();
    const type = msg.type();
    if (text.includes('Dashboard connected')) collected.socketConnectCount++;
    if (/feature[\s_-]?policy/i.test(text) || /skipping unsupported feature/i.test(text)) {
      collected.featurePolicy.push(text);
      return;
    }
    if (/clear-site-data/i.test(text)) { collected.clearSiteData.push(text); return; }
    if (/could not (parse|load) css|css( parse)? error/i.test(text)) { collected.cssErrors.push(text); return; }
    if (/\.map(\?|$)/i.test(text) && /source map|devtools/i.test(text)) { collected.sourceMapErrors.push(text); return; }
    if (type === 'error') {
      if (/screenshot|\/api\/content\/.*\/(file|screenshot)/i.test(text) && /401/.test(text)) {
        collected.screenshot401.push(text);
      } else {
        collected.otherConsoleErrors.push(text);
      }
    }
  });
  page.on('pageerror', (err) => { collected.jsErrors.push(err.message); });
  page.on('requestfailed', (req) => {
    const url = req.url();
    if (url.includes('sw-admin.js') || url.includes('cloudflareinsights')) return;
    if (/\.map(\?|$)/i.test(url)) { collected.sourceMapErrors.push(`${url} - ${req.failure()?.errorText || 'failed'}`); return; }
    if (/screenshot|\/api\/content\/.*\/(file|screenshot)/i.test(url)) { collected.screenshot401.push(`${url} - ${req.failure()?.errorText || 'failed'}`); return; }
    collected.otherConsoleErrors.push(`${url} - ${req.failure()?.errorText || 'failed'}`);
  });
  page.on('response', (response) => {
    const url = response.url();
    if (response.status() === 401 && /\/api\/(content|displays|screenshots)/i.test(url)) {
      collected.screenshot401.push(`${url} - HTTP 401`);
    }
  });
  page.on('page', () => { collected.reloadCount++; });
  return collected;
}

function assertCleanConsole(collected, context = '') {
  const label = context ? ` (${context})` : '';
  const fail = (cat, items) => { if (items.length) throw new Error(`${cat}${label}:\n  ${items.slice(0, 12).join('\n  ')}`); };
  fail('Feature Policy warnings from application iframes', collected.featurePolicy);
  fail('Clear-Site-Data warnings', collected.clearSiteData);
  fail('JavaScript errors', collected.jsErrors);
  fail('CSS parsing errors', collected.cssErrors);
  fail('Unhandled promise rejections', collected.rejections);
  fail('Screenshot 401 responses', collected.screenshot401);
  fail('Application-owned source-map errors', collected.sourceMapErrors);
  fail('Other console/request errors', collected.otherConsoleErrors);
  // A single Socket.IO connection is expected; duplicates indicate a leak.
  if (collected.socketConnectCount > 1) {
    throw new Error(`Duplicate Socket.IO connections${label}: ${collected.socketConnectCount}`);
  }
  // Unintended page reloads during a stable session are a defect.
  if (collected.reloadCount > 1) {
    throw new Error(`Unintended page reloads${label}: ${collected.reloadCount}`);
  }
}

async function setupAuth(page) {
  await page.addInitScript(({ token, user }) => {
    localStorage.setItem('token', token);
    localStorage.setItem('user', JSON.stringify(user));
    localStorage.setItem('rd_onboarded', '1');
  }, { token: authToken, user: authUser });
}

test.describe.configure({ mode: 'serial' });

test.describe('Browser-console acceptance', () => {
  test.beforeAll(async () => {
    await startServer();
    await registerTestUser();
  });
  test.afterAll(() => { killServer(); if (tmpDir) { try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch {} } });

  test('B0. /app does NOT emit Clear-Site-Data on normal loads', async () => {
    const res = await fetch(`${BASE_URL}/app`, { redirect: 'manual' });
    expect(res.status).toBe(200);
    expect(res.headers.get('cache-control').toLowerCase()).toContain('no-store');
    expect(res.headers.get('clear-site-data'), 'no Clear-Site-Data on /app').toBeNull();
  });

  for (const vp of VIEWPORTS) {
    test(`B1. clean console at ${vp.width}x${vp.height}`, async ({ page }) => {
      const collected = attachConsoleCollectors(page);
      await page.setViewportSize(vp);
      await setupAuth(page);
      await page.goto(`${BASE_URL}/app`, { waitUntil: 'domcontentloaded' });
      // Wait for the dashboard shell to mount and the socket to connect.
      await expect(page.locator('.mc-cc-shell, #app, [data-view="control"]')).toBeVisible({ timeout: 30000 });
      await page.waitForTimeout(3000);
      assertCleanConsole(collected, `${vp.width}x${vp.height}`);
      // installHook.js.map is extension-owned: a clean headless profile has no
      // React DevTools, so no installHook source-map noise should appear.
      const installHookNoise = [...collected.sourceMapErrors].filter((m) => /installHook/i.test(m));
      expect(installHookNoise, 'installHook.js.map must not appear in a clean profile').toHaveLength(0);
    });

    test(`B2. stable keyed render — no iframe recreation storm at ${vp.width}x${vp.height}`, async ({ page }) => {
      const collected = attachConsoleCollectors(page);
      await page.setViewportSize(vp);
      await setupAuth(page);
      await page.goto(`${BASE_URL}/app#/control`, { waitUntil: 'domcontentloaded' });
      await expect(page.locator('#app')).toBeVisible({ timeout: 30000 });
      // Let the stage mount and one screenshot/state cycle land.
      await page.waitForTimeout(2500);
      const baseline = await page.evaluate(() => {
        const m = window.__mcStageMetrics || {};
        return { renders: m.renders || 0, creates: m.iframeCreates || 0, removes: m.iframeRemoves || 0, patches: m.inPlacePatches || 0 };
      });
      // Idle soak: routine state pings (screenshots/heartbeats) for several
      // seconds must not recreate iframes — the keyed render patches in place.
      await page.waitForTimeout(6000);
      const after = await page.evaluate(() => {
        const m = window.__mcStageMetrics || {};
        return { renders: m.renders || 0, creates: m.iframeCreates || 0, removes: m.iframeRemoves || 0, patches: m.inPlacePatches || 0 };
      });
      // No structural change occurred, so iframe creation during the idle window
      // must be zero (or at most the in-place patch path dominates).
      expect(after.creates - baseline.creates, 'idle state pings must not recreate iframes').toBeLessThanOrEqual(0);
      assertCleanConsole(collected, `soak ${vp.width}x${vp.height}`);
    });
  }
});
